config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users

  root 'welcome#index'
  get 'welcome/index'

  resources :movies do
    resources :comments
  end
  resources :genres

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ActiveModel::Validations
  validates :user, presence: true
  validates :body, presence: true, length: {in: 5..500}
  validates :rating, numericality: true, :inclusion => 1..10

  belongs_to :movie, class_name: "Movie", foreign_key: :movie_id
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genres_movie
  has_many :movies, through: :genres_movie
end

app/models/genres_movie.rb
class GenresMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, length: { minimum: 1 }
  validates :year, numericality: true, length: { minimum: 4 }
  validates :duration, presence: true, length: { minimum: 5 }
  validates :genres, presence: true
  # validates :director, presence: true, length: { maximum: 100 }
  # validates :writer, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: {in: 5..500}

  has_many :comments,  dependent: :destroy

  has_many :genres_movies
  has_many :genres, through: :genres_movies

  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def tags=(value)
    value = sanitize_tags(value) if value.is_a?(String)

    super(value)
  end

  def average_rating
    self.comments.average(:rating)
  end

  private


  def sanitize_tags(text)
    text.downcase.split.uniq
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies, foreign_key: :user_id
  has_many :comments

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "secret", only: :destroy
  before_action :find_movie

  def show
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.movie = @movie
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "You've successfuly add your comment."
      redirect_to movie_path(@movie)
    else
      render 'movies/show'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "You've successfuly update your comment."
      redirect_to movie_path(@movie)
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "You've delete your comment"
    redirect_to movie_path(@movie)
  end

  private

  def comment_params
    params.require(:comment).permit(:user, :body, :rating)
  end

  def find_movie
    @movie = Movie.find(params[:movie_id])
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :find_genre, only: [:show, :edit, :update, :destroy]

def index
  @genres = Genre.all
end

def show
end

def new
  @genre = Genre.new
end

def edit
end

def create
  @genre = Genre.new(genre_params)
  if @genre.save
    flash[:notice] = "You've successfuly add the genre."
    redirect_to genre_path(@genre)
  else
    render 'new'
  end
end

def update
  if @genre.update(genre_params)
     flash[:notice] = "You've successfuly update the genre."
     redirect_to genre_path(@genre)
  else
    render 'edit'
  end
end

def destroy
  @genre.destroy
  flash[:notice] = "You've delete the genre."
  redirect_to genres_path(@genre)
end

private

  def find_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "secret", except: [:index, :show]
  before_action :find_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_movie, only: [:edit, :update, :destroy]

  def index
    @movies = Movie.all.order(id: :desc)
    @movies = @movies.where("tags @> ARRAY[?]::text[]", params[:q].split(' '))  if params[:q].present?
    #@movies = @movies.where("? = any(tags)", params[:q]) if params[:q].present?
  end

  def show
    @comment = Comment.new
  end

  def new
    @movie = Movie.new
    @user = User.new
  end

  def create
    # render plain: params[:movie].inspect
    @movie = Movie.new(movie_params)
    @movie.user = current_user if current_user
    if @movie.save
      flash[:notice] = "You've successfuly add the movie."
      redirect_to movie_path(@movie)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
       flash[:notice] = "You've successfuly update the movie."
       redirect_to movie_path(@movie)
    else
      render 'edit'
    end
  end

  def destroy
    @movie.destroy
    flash[:notice] = "You've delete the movie."
    redirect_to movies_path(@movie)
  end

  private

  def authorize_movie
    if current_user != @movie.user && !current_user&.admin?
      flash[:alert] = "You are not allowed to be here!"
      redirect_to movies_path
      false
    else
      true
    end
  end

  def movie_params
   params.require(:movie).permit(:title, :year, :image, :duration, :description, :tags, :user, genre_ids: [])
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= simple_format(comment.body) %>
</p>

<p>
  <strong>Your rate:</strong>
  <%= comment.rating %>
</p>

  <%= link_to 'Destroy', movie_comment_path(movie_id: comment.movie.id, id: comment.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-warning" %>

  <%= link_to 'Edit', edit_movie_comment_path(movie_id: comment.movie.id, id: comment.id), class: "btn btn-warning" %>

<hr />

app/views/comments/_form.html.erb
<%= render 'common/errors', model: @comment %>

<%= form_for [@movie, @comment] do |f| %>
  
  <div class="form-group">
    <%= f.label :Comment %><br>
    <%= f.text_area :body, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :Rate_from_1_to_10 %><br>
    <%= f.text_area :rating, class: 'form-control'  %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<%= render 'common/errors', model: @comment %>

<%= form_for [@movie, @comment] do |f| %>
<!-- <%= f.hidden_field :movie_id %> -->

  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :rate %>
    <%= f.text_field :rating, class: 'form-control' %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

  <%= link_to 'Back', @movie, class: "btn btn-warning" %>

app/views/common/_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning" role="alert" id='error_explanation'>

    <h2>
      <%= pluralize(model.errors.count, "error") %> - Data can not be saved:
    </h2>

    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>

app/views/genres/_form.html.erb
<%= render 'common/errors', model: @genre %>

<%= form_for @genre do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genres</h1>

<table class='table table-striped table-dark'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to 'Show', genre_path(genre) %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Delete', genre_path(genre), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'To the Movies', movies_path, class: "btn btn-warning" %>
<%= link_to 'Add Genre', new_genre_path, class: "btn btn-warning" %>


<br>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<p>
  <strong>Movies</strong>
    <% @genre.movies.each do |movie| %>
      <%= link_to movie.title, movie_path(movie),  class: "btn btn-warning" %>
    <% end %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Films</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <p>
        Hello <%= current_user.email %>!<br>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </p>
    <% else %>
      <p>
        <%= link_to 'Sign in', new_user_session_path%><br>
        <%= link_to 'Sign up', new_user_registration_path%>
      </p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="container-fluid">
<%= render 'common/errors', model: @movie %>
<%= form_for @movie, html: { multipart: true } do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %><br>
    <%= f.label :year %>
    <%= f.text_field :year, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :genres %>
    <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name, class: 'form-control' %>
  </div>

  <hr />

  <div class="form-group">
    <%= f.label :duration %>
    <%= f.text_field :duration, class: 'form-control' %>
  </div>

  <hr />

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :tags %><br>
    <%= f.text_field :tags, class: 'form-control' %>
  </div>

  <p>
    <%= f.submit %>
  </p>

<% end %>
</div>

app/views/movies/edit.html.erb
<h1>Edit movie</h1>

  <%= render 'form', movie: @movie  %>
  <%= link_to 'Back', movies_path, class: "btn btn-warning" %>

app/views/movies/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Movies gallery</h1>
  <p class="lead">This is an online database of information about actors, movies, TV shows, and video games.</p>
  <hr class="my-4">
  <p>Find movies, games, TV shows, actors and more...</p>
    <%= form_tag movies_path, method: :get do %>
      <div class="input-group">
        <%= text_field_tag :q, params[:q], class: "form-control" %>
          <span class="input-group-btn">
            <%= submit_tag "Search", class: "btn btn-default" %>
          </span>
      </div>
    <% end %>
  <h2><%= link_to 'New movie', new_movie_path %></h2>
</div>

  <table class='table table-striped table-dark'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Year</th>
        <th>Added by</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
        <th>Rating</th>
      </tr>
    </thead>

    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><i><%= movie.title %></i></td>
          <td><%= movie.year %></td>
          <td><%= movie.user.email %></td>
          <td><%= link_to 'Show', movie_path(movie) %></td>
          <td><% if movie.user == current_user || current_user&.admin? %>
                <%= link_to 'Edit', edit_movie_path(movie) %>
              <% end %></td>
          <td><% if movie.user == current_user || current_user&.admin? %>
                  <%= link_to 'Delete', movie_path(movie), method: :delete, data: {confirm: 'Are you sure?'} %>
              <% end %></td>
          <td><%= movie.average_rating %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <hr />

  <h2>Movies on our base: <%= @movies.count %></h2>
</div>

app/views/movies/new.html.erb
<h1> New movie </h1>

  <%= render 'form', movie: @movie  %>
  <%= link_to 'Back', movies_path, class: "btn btn-warning" %>

app/views/movies/show.html.erb
<h1 style="display: inline;" ><%= @movie.title %></h1>
  <h6 style="display: inline;"> (<%= @movie.year %>)</h6>

<%= image_tag @movie.image.url(:thumb) %>
<hr />

  <table class="table table-bordered table-dark">
    <tbody>
      <tr>
        <th scope="row">Duration</th>
        <td><%= @movie.duration %></td>
      </tr>

        <th scope="row">Genres</th>
          <td><% @movie.genres.each do |genre| %>
            <%= link_to genre.name, genre_path(genre), class: "badge badge-light" %>
          <% end %></td>
    </tbody>
  </table>

<div class="p-3 mb-2 bg-warning text-dark"><%= @movie.description %></div>

<hr />

<h2>Comments</h2>
  <%= render @movie.comments %>
<h2>Add a comment:</h2>
  <% if current_user %>
    <%=render 'comments/form' %>
  <%end%>

  <%= link_to 'Back', movies_path, class: "btn btn-warning" %>

  <% if @movie.user == current_user || current_user&.admin? %>
    <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-warning" %>
  <% end %>
<hr />

  <p>
  <strong> Tags:</strong>
    <% @movie.tags.each do |t| %>
      <%=link_to t, movies_path(q: t), class: "badge badge-dark"%>
    <% end %>
  </p>
<hr />

  <strong>Movie added by:</strong>
  <%= @movie.user.email %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">FILMOVO</h1>
    <p class="lead">Movies descriptions, ratings, opinions</p>
    <p><%= link_to movies_path do %>
       <%= image_tag("Movie.jpg", "data-svg-fallback" => asset_path("Movie.jpg",), :align=> "left" ,:style => "padding-right: 5px;", :size => "200x125") %>
    <% end %></p>
  <hr />
  <%= link_to 'Movies Gallery', controller: "movies" %>
  <%= link_to 'Genres', controller: "genres" %>
</div>